name: CI - Tests

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run tests and generate JUnit report
        env:
          JEST_JUNIT_OUTPUT: test-results/junit.xml
        run: |
          npm test -- --reporters=default --reporters=jest-junit
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: test-results/junit.xml
